import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

/**
 * The hydrate adapter ships as a CommonJS bundle that is generated by the
 * `@public-ui/components` Stencil build (output target `dist-hydrate-script`,
 * see `packages/components/stencil.config.ts`). We load it through
 * `createRequire` so the named exports resolve reliably regardless of how the
 * generated bundle exposes them.
 *
 * @returns {{ renderToString: Function, streamToString: Function }}
 */
function loadHydrate() {
	try {
		return require('@public-ui/hydrate');
	} catch (error) {
		if (error && (error.code === 'MODULE_NOT_FOUND' || error.code === 'ERR_MODULE_NOT_FOUND')) {
			const hint = new Error(
				'@public-ui/hydrate is not built yet. Run `pnpm --filter @public-ui/sample-ssr build:deps` ' +
					'(this builds @public-ui/components, which generates the hydrate bundle) and try again.',
			);
			hint.code = 'HYDRATE_NOT_BUILT';
			hint.cause = error;
			throw hint;
		}
		throw error;
	}
}

/**
 * Options passed to `renderToString`.
 *
 * `clientHydrateAnnotations: false` keeps the markup clean for a pure SSR / no
 * JavaScript scenario. `destroyDocument`/`destroyWindow` make sure the renderer
 * releases its resources after every call so the process can exit cleanly.
 *
 * @see https://stenciljs.com/docs/hydrate-app
 */
export const DEFAULT_OPTIONS = Object.freeze({
	clientHydrateAnnotations: false,
	destroyDocument: true,
	destroyWindow: true,
	prettyHtml: true,
	removeHtmlComments: true,
	removeUnusedStyles: true,
	serializeToHtml: true,
	timeout: 5000,
});

/**
 * A small, representative KoliBri fragment. It renders the two components the
 * spike (issue #5494) explicitly asks for — `kol-button` and `kol-input-text` —
 * inside a `kol-form`, plus a heading for context.
 */
export const FRAGMENT = [
	'<kol-heading _label="KoliBri server-side rendering" _level="1"></kol-heading>',
	'<p>This page was rendered on the server with <code>@public-ui/hydrate</code>. The components below carry their',
	'markup and scoped styles as Declarative Shadow DOM, so they are correct and visible without any client-side JavaScript.</p>',
	'<kol-form>',
	'\t<kol-input-text _label="Search term" _name="q" _placeholder="e.g. KoliBri"></kol-input-text>',
	'\t<kol-button _label="Search" _type="submit" _variant="primary"></kol-button>',
	'</kol-form>',
].join('\n');

/**
 * Hydrates a KoliBri HTML fragment on the server.
 *
 * @param {string} [html] HTML containing KoliBri component tags.
 * @param {object} [options] Overrides merged onto {@link DEFAULT_OPTIONS}.
 * @returns {Promise<{ html: string, diagnostics: unknown[] }>} The hydrated markup and renderer diagnostics.
 */
export async function renderFragment(html = FRAGMENT, options = {}) {
	const { renderToString } = loadHydrate();
	const result = await renderToString(html, { ...DEFAULT_OPTIONS, ...options });
	return {
		html: typeof result?.html === 'string' ? result.html : '',
		diagnostics: Array.isArray(result?.diagnostics) ? result.diagnostics : [],
	};
}

/**
 * Extracts the `<body>` content from a serialized HTML document. The hydrate
 * adapter always returns a full document, so we lift out the hydrated markup to
 * embed it into our own document shell.
 *
 * @param {string} document Serialized HTML document.
 * @returns {string} The inner HTML of the `<body>` element.
 */
function extractBody(document) {
	const match = document.match(/<body[^>]*>([\s\S]*)<\/body>/i);
	return (match ? match[1] : document).trim();
}

/**
 * Wraps hydrated markup into a complete, standalone HTML5 document.
 *
 * @param {string} bodyHtml Hydrated markup to place inside `<body>`.
 * @returns {string} A full HTML document string.
 */
function documentShell(bodyHtml) {
	return `<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>KoliBri · Server-side rendering demo</title>
		<style>
			/*
			 * Stencil's hydrate output flags every host element as hidden
			 * (style="visibility: hidden;") so a client runtime can reveal it
			 * after hydration. For a no-JavaScript SSR page we reveal the
			 * already-hydrated components ourselves — an !important rule in a
			 * stylesheet outranks the non-important inline style.
			 */
			[class~='hydrated'] {
				visibility: visible !important;
			}

			body {
				margin: 0 auto;
				max-width: 48rem;
				padding: 2rem 1rem;
				font-family: Verdana, Arial, sans-serif;
			}

			kol-form {
				display: block;
				margin-top: 1.5rem;
			}
		</style>
	</head>
	<body>
${bodyHtml}
	</body>
</html>
`;
}

/**
 * Renders the demo fragment and returns a complete HTML document ready to be
 * sent to a browser or written to disk.
 *
 * @param {string} [html] HTML containing KoliBri component tags.
 * @param {object} [options] Overrides merged onto {@link DEFAULT_OPTIONS}.
 * @returns {Promise<{ html: string, diagnostics: unknown[] }>} The full document and renderer diagnostics.
 */
export async function renderDocument(html = FRAGMENT, options = {}) {
	const result = await renderFragment(html, options);
	return {
		html: documentShell(extractBody(result.html)),
		diagnostics: result.diagnostics,
	};
}
