import { KoliBri } from '@public-ui/schema';
import { css } from './cssTag';

// Informationstechnikzentrum Bund
export const ITZBund = KoliBri.createTheme('itzbund', {
	GLOBAL: css``,
	'KOL-BUTTON': css``,
	'KOL-BUTTON-GROUP': css``,
	'KOL-LINK-BUTTON': css``,
	'KOL-PAGINATION': css``,
	'KOL-BUTTON-LINK': css``,
	'KOL-INPUT-TEXT': css``,
	'KOL-INPUT-PASSWORD': css``,
	'KOL-INPUT-NUMBER': css``,
	'KOL-INPUT-DATE': css``,
	'KOL-INPUT-EMAIL': css``,
	'KOL-INPUT-FILE': css``,
	'KOL-TEXTAREA': css``,
	'KOL-ALERT': css``,
	'KOL-HEADING': css``,
	'KOL-BADGE': css``,
	'KOL-INDENTED-TEXT': css``,
	'KOL-LINK': css``,
	'KOL-BREADCRUMB': css``,
	'KOL-SPIN': css``,
	'KOL-PROGRESS': css``,
	'KOL-SELECT': css``,
	'KOL-INPUT-COLOR': css``,
	'KOL-ACCORDION': css``,
	'KOL-TABLE': css``,
	'KOL-NAV': css``,
	'KOL-CARD': css``,
	'KOL-INPUT-CHECKBOX': css``,
	'KOL-INPUT-RADIO': `/* INPUT */`,
	'KOL-TOAST-CONTAINER': ``,
	'KOL-TABS': ``,
	'KOL-SKIP-NAV': ``,
	'KOL-SPLIT-BUTTON': ``,
});
