dod:
  - Meaningful title and valuable description in the pull request
  - Pull request is linked to an issue
  - All changes relate to the issue
  - A11y tests performed successfully
  - Code review carried out successfully
  - Manual test performed successfully
