packages:
  - packages/adapters/angular/*
  - packages/adapters/hydrate*
  - packages/adapters/preact*
  - packages/adapters/react*
  - packages/adapters/solid*
  - packages/adapters/svelte
  - packages/adapters/vue
  - packages/components
  - packages/icons
  - packages/ecl-icons
  - packages/samples/angular
  - packages/samples/presentation
  - packages/samples/react
  - packages/test-tag-name-transformer
  - packages/themes/bwst
  - packages/themes/default
  - packages/themes/desy
  - packages/themes/ecl
  - packages/themes/kern
  - packages/themes
  - packages/tools/benchmark-tests
  - packages/tools/eslint-config
  - packages/tools/kolibri-cli
  - packages/tools/hydrate-server
  - packages/tools/mcp
  - packages/tools/stylelint-rules
  - packages/tools/visual-tests
allowBuilds:
  '@evilmartians/lefthook': true
  '@modelcontextprotocol/ext-apps': true
  '@parcel/watcher': true
  '@swc/core': true
  chromedriver: true
  edgedriver: true
  esbuild: true
  geckodriver: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  ttf2woff2: true
  unrs-resolver: true
overrides:
  brace-expansion@<1.1.18: '>=1.1.18'
  brace-expansion@>=4.0.0 <5.0.9: '>=5.0.9'
  fast-uri@>=3.0.0 <3.1.5: '>=3.1.5'
  fast-uri@>=4.0.0 <4.1.2: '>=4.1.2'
  ip-address@<=10.3.0: '>=10.3.1'
  ip-address@>=10.1.1 <=10.2.0: '>=10.2.1'
  ip-address@>=10.1.1 <=10.2.1: '>=10.2.2'
