packages:
  - 'packages/adapters/angular/*'
  - 'packages/adapters/hydrate*'
  - 'packages/adapters/preact*'
  - 'packages/adapters/react*'
  - 'packages/adapters/solid*'
  - 'packages/adapters/vue'
  - 'packages/components'
  - 'packages/create-kolibri'
  - 'packages/designer'
  - 'packages/samples/angular'
  - 'packages/samples/react'
  - 'packages/samples/ssr'
  - 'packages/schema'
  - 'packages/themes'
  - 'packages/themes/bmf'
  - 'packages/themes/bzst'
  - 'packages/themes/default'
  - 'packages/themes/ecl'
  - 'packages/themes/itzbund'
  - 'packages/themes/mfm'
  - 'packages/themes/zoll'
  - 'packages/tools/kolibri-cli'
  - 'packages/tools/visual-tests'
