packages:
  - 'packages/adapters/angular/*'
  - 'packages/adapters/hydrate*'
  - 'packages/adapters/preact*'
  - 'packages/adapters/react*'
  - 'packages/adapters/solid*'
  - 'packages/adapters/vue'
  - 'packages/components'
  - 'packages/designer'
  - 'packages/samples/angular'
  - 'packages/samples/react'
  - 'packages/samples/vue'
  - 'packages/test-tag-name-transformer'
  - 'packages/themes'
  - 'packages/themes/bmf'
  - 'packages/themes/default'
  - 'packages/themes/ecl'
  - 'packages/themes/itzbund'
  - 'packages/tools/kolibri-cli'
  - 'packages/tools/visual-tests'
