import { AbstractTask } from '../../abstract-task';
import { AbbrRenamePropertyTitleToLabel } from './abbr';
import { AccordionRenamePropertyHeadingToLabel } from './accordion';
import { BadgeRemovePropertyHideLabel, BadgeRemovePropertyIconOnly, BadgeRenamePropertyIconOnlyToHideLabel } from './badge';
import { BreadcrumbRenamePropertyAriaLabelToLabel } from './breadcrumb';
import { ButtonRemovePropertyAriaCurrent, ButtonRemovePropertyAriaLabel, ButtonRenamePropertyIconOnlyToHideLabel } from './button';
import { ButtonLinkRemovePropertyAriaCurrent, ButtonLinkRemovePropertyAriaLabel, ButtonLinkRenamePropertyIconOnlyToHideLabel } from './button-link';
import { CardRenamePropertyHeadingToLabel, CardRenamePropertyHeadlineToLabel } from './card';
import { DetailsRenamePropertySummaryToLabel } from './details';
import { IconRemovePropertyPart, IconRenamePropertyAriaLabelToLabel } from './icon';
import { InputCheckboxRenamePropertyTypeToVariant } from './input-checkbox';
import { InputColorRenamePropertyListToSuggestions } from './input-color';
import { InputDateRenamePropertyListToSuggestions } from './input-date';
import { InputEmailRenamePropertyListToSuggestions } from './input-email';
import { InputNumberRenamePropertyListToSuggestions } from './input-number';
import { InputRadioRenamePropertyListToSuggestions } from './input-radio';
import { InputRangeRenamePropertyListToSuggestions } from './input-range';
import { InputTextRenamePropertyListToSuggestions } from './input-text';
import { LinkGroupRemovePropertyOrdered, LinkGroupRenamePropertyAriaLabelToLabel } from './link-group';
import { NavRemovePropertyHasCompactButton, NavRenamePropertyAriaLabelToLabel, NavRenamePropertyCompactToHideLabel } from './nav';
import { PaginationRenamePropertyCountToTotal } from './pagination';
import { ProgressRenamePropertyTypeToVariant } from './progress';
import { QuoteRenamePropertyCaptionToLabel } from './quote';
import { SelectRenamePropertyHeightToRows, SelectRenamePropertyListToOptions } from './select';
import { SkipNavButtonRenamePropertyAriaLabelToLabel } from './skip-nav';
import { SpanRenamePropertyIconOnlyToHideLabel } from './span';
import { SplitButtonRemovePropertyAriaLabel } from './split-button';
import { TableRenamePropertyCaptionToLabel } from './table';
import { TabsRenamePropertyAriaLabelToLabel, TabsRenamePropertyTabAlignToAlign } from './tabs';
import { ToastRenamePropertyHeadingToLabel } from './toast';
import { VersionRenamePropertyVersionToLabel } from './version';

export const v1Tasks: AbstractTask[] = [];
v1Tasks.push(AbbrRenamePropertyTitleToLabel);
v1Tasks.push(AccordionRenamePropertyHeadingToLabel);
v1Tasks.push(BadgeRemovePropertyHideLabel);
v1Tasks.push(BadgeRemovePropertyIconOnly);
v1Tasks.push(BadgeRenamePropertyIconOnlyToHideLabel);
v1Tasks.push(BreadcrumbRenamePropertyAriaLabelToLabel);
v1Tasks.push(ButtonLinkRemovePropertyAriaCurrent);
v1Tasks.push(ButtonLinkRemovePropertyAriaLabel);
v1Tasks.push(ButtonLinkRenamePropertyIconOnlyToHideLabel);
v1Tasks.push(ButtonRemovePropertyAriaCurrent);
v1Tasks.push(ButtonRemovePropertyAriaLabel);
v1Tasks.push(ButtonRenamePropertyIconOnlyToHideLabel);
v1Tasks.push(CardRenamePropertyHeadingToLabel);
v1Tasks.push(CardRenamePropertyHeadlineToLabel);
v1Tasks.push(DetailsRenamePropertySummaryToLabel);
v1Tasks.push(IconRemovePropertyPart);
v1Tasks.push(IconRenamePropertyAriaLabelToLabel);

v1Tasks.push(InputCheckboxRenamePropertyTypeToVariant);
v1Tasks.push(InputColorRenamePropertyListToSuggestions);
v1Tasks.push(InputDateRenamePropertyListToSuggestions);
v1Tasks.push(InputEmailRenamePropertyListToSuggestions);
v1Tasks.push(InputNumberRenamePropertyListToSuggestions);
v1Tasks.push(InputRadioRenamePropertyListToSuggestions);
v1Tasks.push(InputRangeRenamePropertyListToSuggestions);
v1Tasks.push(InputTextRenamePropertyListToSuggestions);

v1Tasks.push(LinkGroupRenamePropertyAriaLabelToLabel);
v1Tasks.push(LinkGroupRemovePropertyOrdered);
v1Tasks.push(NavRenamePropertyAriaLabelToLabel);
v1Tasks.push(NavRenamePropertyCompactToHideLabel);
v1Tasks.push(NavRemovePropertyHasCompactButton);
v1Tasks.push(NavRenamePropertyCompactToHideLabel);
v1Tasks.push(PaginationRenamePropertyCountToTotal);
v1Tasks.push(ProgressRenamePropertyTypeToVariant);
v1Tasks.push(QuoteRenamePropertyCaptionToLabel);
v1Tasks.push(SelectRenamePropertyHeightToRows);
v1Tasks.push(SelectRenamePropertyListToOptions);
v1Tasks.push(SkipNavButtonRenamePropertyAriaLabelToLabel);
v1Tasks.push(SpanRenamePropertyIconOnlyToHideLabel);
v1Tasks.push(SplitButtonRemovePropertyAriaLabel);
v1Tasks.push(TableRenamePropertyCaptionToLabel);
v1Tasks.push(TabsRenamePropertyAriaLabelToLabel);
v1Tasks.push(TabsRenamePropertyTabAlignToAlign);
v1Tasks.push(ToastRenamePropertyHeadingToLabel);
v1Tasks.push(VersionRenamePropertyVersionToLabel);
