import { AbstractTask } from '../../abstract-task';
import { AbbrRenamePropertyTitleToLabel } from './abbr';
import { AccordionRenamePropertyHeadingToLabel } from './accordion';
import { BadgeRemovePropertyHideLabel, BadgeRemovePropertyIconOnly, BadgeRenamePropertyIconOnlyToHideLabel } from './badge';
import { BreadcrumbRenamePropertyAriaLabelToLabel } from './breadcrumb';
import { ButtonRemovePropertyAriaCurrent, ButtonRemovePropertyAriaLabel, ButtonRenamePropertyIconOnlyToHideLabel } from './button';
import { ButtonLinkRemovePropertyAriaCurrent, ButtonLinkRemovePropertyAriaLabel, ButtonLinkRenamePropertyIconOnlyToHideLabel } from './button-link';
import { CardRenamePropertyHeadingToLabel, CardRenamePropertyHeadlineToLabel } from './card';
import { DetailsRenamePropertySummaryToLabel } from './details';
import { IconRemovePropertyPart, IconRenamePropertyAriaLabelToLabel } from './icon';
import { LinkGroupRenamePropertyAriaLabelToLabel } from './link-group';
import { NavRenamePropertyAriaLabelToLabel } from './nav';
import { TabRenamePropertyTabAlignToAlgin } from './tabs';

export const v1Tasks: AbstractTask[] = [];
v1Tasks.push(AbbrRenamePropertyTitleToLabel);
v1Tasks.push(AccordionRenamePropertyHeadingToLabel);
v1Tasks.push(BadgeRemovePropertyHideLabel);
v1Tasks.push(BadgeRemovePropertyIconOnly);
v1Tasks.push(BadgeRenamePropertyIconOnlyToHideLabel);
v1Tasks.push(BreadcrumbRenamePropertyAriaLabelToLabel);
v1Tasks.push(ButtonLinkRemovePropertyAriaCurrent);
v1Tasks.push(ButtonLinkRemovePropertyAriaLabel);
v1Tasks.push(ButtonLinkRenamePropertyIconOnlyToHideLabel);
v1Tasks.push(ButtonRemovePropertyAriaCurrent);
v1Tasks.push(ButtonRemovePropertyAriaLabel);
v1Tasks.push(ButtonRenamePropertyIconOnlyToHideLabel);
v1Tasks.push(CardRenamePropertyHeadingToLabel);
v1Tasks.push(CardRenamePropertyHeadlineToLabel);
v1Tasks.push(DetailsRenamePropertySummaryToLabel);
v1Tasks.push(IconRemovePropertyPart);
v1Tasks.push(IconRenamePropertyAriaLabelToLabel);
v1Tasks.push(LinkGroupRenamePropertyAriaLabelToLabel);
v1Tasks.push(NavRenamePropertyAriaLabelToLabel);
v1Tasks.push(TabRenamePropertyTabAlignToAlgin);
