import { Theme } from '@a11y-ui/core';

enum TagEnum {
	'abbr',
	'accordion',
	'alert',
	'badge',
	'breadcrumb',
	'button',
	'button-group',
	'button-link',
	'card',
	'details',
	'form',
	'heading',
	'icon',
	'indented-text',
	'input-checkbox',
	'input-color',
	'input-date',
	'input-file',
	'input-email',
	'input-number',
	'input-password',
	'input-radio',
	'input-range',
	'input-text',
	'link',
	'link-button',
	'link-group',
	'modal',
	'nav',
	'pagination',
	'progress',
	'select',
	'skip-nav',
	'spin',
	'symbol',
	'table',
	'tabs',
	'textarea',
	'toast',
	'tooltip',
}

enum KeyEnum {
	'alert-error-label',
	'alert-info-label',
	'alert-warning-label',
	'alert-success-label',
	'form-required-advise',
	'link-target-advise',
	'logo-label',
	'nav-label-close',
	'nav-label-open',
	'pagination-label-first',
	'pagination-label-last',
	'pagination-label-next',
	'pagination-label-previous',
	'pagination-label-current',
	'spin-label-busy',
	'spin-label-finished',
	'table-button-sort-label',
	'table-pagination-label',
	'table-pagination-sites-no',
	'table-pagination-sites-yes',
	'tabs-button-add-label',
	'tabs-button-close-label',
	'toast-button-close-label',
}

export const KoliBri = new Theme<'kol', keyof typeof KeyEnum, keyof typeof TagEnum>('kol', KeyEnum, TagEnum);
