export enum TagEnum {
	'abbr',
	'accordion',
	// 'accordion-group', // TODO: github pr link
	'alert',
	'avatar',
	'badge',
	'breadcrumb',
	'button',
	'button-group',
	'button-link',
	'card',
	// 'combobox', // TODO: github pr link
	'details',
	'form',
	'heading',
	'icon',
	'image',
	'indented-text',
	'input-checkbox',
	'input-color',
	'input-date',
	'input-email',
	'input-file',
	'input-number',
	'input-password',
	'input-radio',
	'input-range',
	'input-text',
	// 'kolibri', // this component may not be redesigned
	'link',
	'link-button',
	'link-group',
	// 'logo', // this component may not be redesigned
	'modal',
	'nav',
	'pagination',
	'progress',
	'select',
	// 'separator', // TODO: github pr link
	// 'sidebar', // TODO: github pr link
	'skip-nav',
	'spin',
	'split-button',
	'symbol',
	'table',
	'tabs',
	'textarea',
	'toast-container',
	// 'toolbar', // TODO: github pr link
	'tooltip',
	'tree',
	'tree-item',
}
