export enum TagEnum {
	'abbr',
	'accordion',
	'accordion-group', // TODO: github pr link
	'alert',
	'avatar',
	'badge',
	'breadcrumb',
	'button',
	'button-group',
	'button-link',
	'card',
	'details',
	'form',
	'heading',
	'icon',
	'image',
	'indented-text',
	'input-checkbox',
	'input-color',
	'input-date',
	'input-file',
	'input-email',
	'input-number',
	'input-password',
	'input-radio',
	'input-range',
	'input-text',
	'link',
	'link-button',
	'link-group',
	'modal',
	'nav',
	'pagination',
	'popover',
	'progress',
	'select',
	'separator', // TODO: github pr link
	'skip-nav',
	'spin',
	'symbol',
	'table',
	'tabs',
	'textarea',
	'toast',
	'toolbar', // TODO: github pr link
	'tooltip',
}
