name: pnpm Setup
runs:
  using: 'composite'
  steps: # https://pnpm.io/continuous-integration#github-actions
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
      shell: bash
