import { KoliBri } from '@public-ui/schema';

// Europa Component Library - European Commission | https://ec.europa.eu/component-library/ec/
export const ECL_EC = KoliBri.createTheme('ecl-ec', {
	GLOBAL:
		':host {--kolibri-border-color: unset;--kolibri-border-radius: unset;--kolibri-border-width: unset;--kolibri-color-error: unset;--kolibri-color-info: unset;--kolibri-color-success: unset;--kolibri-color-warning: unset;--kolibri-color-primary: unset;--kolibri-color-secondary: unset;--kolibri-color-normal: unset;--kolibri-color-danger: unset;--kolibri-color-ghost: unset;--kolibri-color-disabled: unset;--kolibri-color-text: unset;--kolibri-color-visited: unset;--kolibri-font-family: unset;--kolibri-font-size: unset;--kolibri-spacing: unset;}:host {--color-blue: #004494;--color-yellow: #ffd617;--color-grey: #404040;--color-blue-130: #002f67;--color-blue-120: #003776;--color-blue-110: #003d84;--color-blue-100: var(--color-blue);--color-blue-75: #4073af;--color-blue-50: #bfd0e4;--color-blue-25: #bfd0e4;--color-blue-5: #f2f5f9;--color-yellow-120: #f8ae21;--color-yellow-110: #fbc11d;--color-yellow-100: var(--color-yellow);--color-yellow-75: #ffde39;--color-yellow-50: #ffe879;--color-yellow-25: #fff4bb;--color-grey-100: var(--color-grey);--color-grey-75: #707070;--color-grey-50: #9f9f9f;--color-grey-25: #cfcfcf;--color-grey-20: #d9d9d9;--color-grey-15: #e3e3e3;--color-grey-10: #ebebeb;--color-grey-5: #f5f5f5;--color-grey-3: #f9f9f9;--color-blue-n: #006fb4;--color-orange: #f29527;--color-green: #467a39;--color-red: #da2131;--color-red-1xx: #981722;--color-black: #000;--color-white: #fff;--font-family: Arial, sans-serif;--font-size: 16px;--font-weight: 400;--font-weight-bold: 600;--line-height: 1.5em;--line-height-heading: 1.2em; /* ?! */--spacing-4xl: 64px;--spacing-3xl: 48px;--spacing-2xl: 40px;--spacing-xl: 32px;--spacing-l: 24px;--spacing-m: 16px;--spacing-s: 12px;--spacing-xs: 8px;--spacing-2xs: 4px; /* ?! */}:host {font-family: var(--font-family);font-size: var(--font-size);}a,button {font-size: var(--font-size);outline: none;}h1,h2,h3,h4,h5,h6 {font-weight: var(--font-weight-bold);line-height: var(--line-height-heading);}p {font-weight: var(--font-weight);}',
	'KOL-HEADING':
		'h1 {font-size: 2rem;line-height: 2.5rem;}h2 {font-size: 1.75rem;line-height: 2rem;}h3 {font-size: 1.5rem;line-height: 1.75rem;}h4 {font-size: 1.25rem;line-height: 1.75rem;}h5 {font-size: 1rem;line-height: 1.5rem;}h6 {color: rgb(234, 0, 255);}',
	'KOL-ACCORDION':
		':host > div {background-color: var(--color-grey-5);border-color: var(--color-grey-25);border-style: solid;border-width: 1px;}:host > div .headline button {text-align: left;width: 100%;padding: 0 var(--spacing-m);display: flex;place-items: center;}:host > div .headline button kol-icon {margin-bottom: 0.75rem;margin-inline-end: 1rem;margin-inline-start: 0;margin-top: 0.75rem;}:host > div .headline button span {color: var(--color-grey);font-weight: var(--font-weight-bold);padding: 0.75rem 0;width: 100%;}:host > div[part*="open"] .headline button span {border-bottom: 1px solid var(--color-grey);}:host > div .headline button:focus,:host > div .headline button:hover {background-color: var(--color-grey-25);}:host > div .headline button:focus {outline: 2px solid var(--color-blue);outline-offset: -2px;}div[part="content"] {padding: var(--spacing-s) var(--spacing-m);}',
	'KOL-INDENTED-TEXT':
		':host > div {border-end-start-radius: 0;border-inline-start: 10px solid #ffd617;border-start-start-radius: 0;padding-bottom: 1rem;padding-inline-start: 1.5rem;padding-top: 1rem;margin: 0;}',
	'KOL-BUTTON':
		':host {--kolibri-spacing: 0.25rem;}a,button {appearance: none;background: none;outline: none;text-decoration: none;}a kol-span-wc,button kol-span-wc {appearance: none;background: none;border-radius: 0;border-style: solid;border-width: 2px;font-weight: var(--font-weight-bold);margin: 0;padding: 0.75rem;}a:focus kol-span-wc,button:focus kol-span-wc {outline-offset: -4px;outline-width: 2px;outline-style: solid;}button.ghost:focus kol-span-wc {outline-offset: -2px;}.primary a kol-span-wc,.primary button kol-span-wc {background-color: var(--color-blue);border-color: var(--color-blue);color: var(--color-white);}.primary a:focus kol-span-wc,.primary button:focus kol-span-wc {outline-color: var(--color-white);}.primary a:hover kol-span-wc,.primary button:hover kol-span-wc {background-color: var(--color-blue-130);border-color: var(--color-blue-130);}.secondary a kol-span-wc,.secondary button kol-span-wc {background-color: var(--color-white);border-color: var(--color-blue);color: var(--color-blue);}.secondary a:focus kol-span-wc,.secondary button:focus kol-span-wc {outline-color: var(--color-blue);outline-offset: -6px;}.secondary a:hover kol-span-wc,.secondary button:hover kol-span-wc {border-color: var(--color-blue-130);color: var(--color-blue-130);}.normal a kol-span-wc, /* CTA */.normal button kol-span-wc {background-color: var(--color-yellow);border-color: var(--color-yellow);color: var(--color-black);}.normal a:hover kol-span-wc, /* CTA */.normal button:hover kol-span-wc {background-color: var(--color-yellow-120);border-color: var(--color-yellow-120);}.danger a kol-span-wc,.danger button kol-span-wc {background-color: var(--color-red);border-color: var(--color-red);color: var(--color-white);}.danger a:hover kol-span-wc,.danger button:hover kol-span-wc {background-color: var(--color-red);border-color: var(--color-red);}.ghost a kol-span-wc,.ghost button kol-span-wc {background-color: transparent;border-color: transparent;color: var(--color-blue);}.ghost a:focus kol-span-wc,.ghost button:focus kol-span-wc {outline-color: var(--color-blue);}.ghost a:hover kol-span-wc,.ghost button:hover kol-span-wc {color: var(--color-blue-130);}',
	'KOL-LINK-BUTTON':
		':host {--kolibri-spacing: 0.25rem;}a,button {appearance: none;background: none;outline: none;text-decoration: none;}a kol-span-wc,button kol-span-wc {appearance: none;background: none;border-radius: 0;border-style: solid;border-width: 2px;font-weight: var(--font-weight-bold);margin: 0;padding: 0.75rem;}a:focus kol-span-wc,button:focus kol-span-wc {outline-offset: -4px;outline-width: 2px;outline-style: solid;}button.ghost:focus kol-span-wc {outline-offset: -2px;}.primary a kol-span-wc,.primary button kol-span-wc {background-color: var(--color-blue);border-color: var(--color-blue);color: var(--color-white);}.primary a:focus kol-span-wc,.primary button:focus kol-span-wc {outline-color: var(--color-white);}.primary a:hover kol-span-wc,.primary button:hover kol-span-wc {background-color: var(--color-blue-130);border-color: var(--color-blue-130);}.secondary a kol-span-wc,.secondary button kol-span-wc {background-color: var(--color-white);border-color: var(--color-blue);color: var(--color-blue);}.secondary a:focus kol-span-wc,.secondary button:focus kol-span-wc {outline-color: var(--color-blue);outline-offset: -6px;}.secondary a:hover kol-span-wc,.secondary button:hover kol-span-wc {border-color: var(--color-blue-130);color: var(--color-blue-130);}.normal a kol-span-wc, /* CTA */.normal button kol-span-wc {background-color: var(--color-yellow);border-color: var(--color-yellow);color: var(--color-black);}.normal a:hover kol-span-wc, /* CTA */.normal button:hover kol-span-wc {background-color: var(--color-yellow-120);border-color: var(--color-yellow-120);}.danger a kol-span-wc,.danger button kol-span-wc {background-color: var(--color-red);border-color: var(--color-red);color: var(--color-white);}.danger a:hover kol-span-wc,.danger button:hover kol-span-wc {background-color: var(--color-red);border-color: var(--color-red);}.ghost a kol-span-wc,.ghost button kol-span-wc {background-color: transparent;border-color: transparent;color: var(--color-blue);}.ghost a:focus kol-span-wc,.ghost button:focus kol-span-wc {outline-color: var(--color-blue);}.ghost a:hover kol-span-wc,.ghost button:hover kol-span-wc {color: var(--color-blue-130);}',
	'KOL-BADGE':
		':host {--kolibri-spacing: 0.25rem;}:host > span > kol-span-wc {font: normal normal var(--font-weight) 0.875rem/1rem var(--font-family);padding: calc(0.5rem - 1px) calc(0.75rem - 1px);text-transform: uppercase;}',
	'KOL-ALERT':
		':host > div {background-color: var(--color-white);}:host > div.card {border-style: solid;border-width: 2px;}:host > div.msg {border: none;}:host .msg .heading kol-icon {font-size: 1.5em;margin: var(--spacing-2xs);}:host .msg .heading > div {padding: var(--spacing-2xs);}:host .card {padding-bottom: 1.5rem;padding-inline-end: 0.5rem;padding-inline-start: 1.5rem;padding-top: 1.5rem;}:host .card .heading {gap: 0.5rem;}:host .card .content {margin-left: 2.5rem;}:host .card .heading kol-icon {font-size: 2rem;}:host .default {border-color: var(--color-grey);}:host .default .heading kol-icon {color: var(--color-grey);}:host .error {border-color: var(--color-red);}:host .error .heading kol-icon {color: var(--color-red);}:host .info {border-color: var(--color-blue);}:host .info .heading kol-icon {color: var(--color-blue);}:host .success {border-color: var(--color-green);}:host .success .heading kol-icon {color: var(--color-green);}:host .warning {border-color: var(--color-orange);}:host .warning .heading kol-icon {color: var(--color-orange);}',
	'KOL-TABS':
		':host {--kolibri-spacing: 0.25rem;}kol-button-group-wc {border-bottom: 1px solid var(--color-grey-25);margin-bottom: -1px;}kol-button-group-wc button {border: none;margin-bottom: -1px;}kol-button-group-wc button kol-span-wc {padding: 0.5rem;min-height: 44px;min-width: 44px;}kol-button-group-wc button.selected kol-span-wc {border-color: var(--color-grey-25);border-style: solid;border-width: 1px;border-bottom-color: white;border-top-color: var(--color-blue);box-shadow: 0 -3px var(--color-blue);font-weight: var(--font-weight-bold);color: var(--color-blue);}kol-button-group-wc button:hover:not(:disabled) kol-span-wc {color: var(--color-blue-130);}kol-button-group-wc button:focus kol-span-wc {outline-color: var(--color-blue-130);outline-style: solid;outline-width: 2px;}',
	'KOL-LINK':
		':host {--kolibri-spacing: 0.25rem;}a,button {appearance: none;color: var(--color-blue);text-decoration: underline;}a:hover,button:hover {color: var(--color-blue-130);}',
	'KOL-BUTTON-LINK':
		':host {--kolibri-spacing: 0.25rem;}a,button {appearance: none;color: var(--color-blue);text-decoration: underline;}a:hover,button:hover {color: var(--color-blue-130);}',
	'KOL-BREADCRUMB':
		':host {font: normal normal 400 0.875rem/1rem arial, sans-serif;font-weight: var(--font-weight-bold);}kol-icon::part(icon separator)::before {color: var(--color-blue);}li:last-child {color: var(--color-grey-75);}kol-icon[exportparts*="separator"] {margin-inline-end: 0.5rem;margin-inline-start: 0.5rem;padding: 0;}',
	'KOL-DETAILS': 'details > kol-indented-text {margin: 0.175rem;padding: 0;}',
	'KOL-PROGRESS':
		':host progress,:host span {display: block;height: 0px;overflow: hidden;width: 0px;}svg line:first-child,svg circle:first-child {fill: transparent;stroke: var(--color-grey-25);}svg line:last-child,svg circle:last-child {stroke: var(--color-blue-130);fill: transparent;}progress {display: none;}',
	'KOL-SPIN':
		'.spin span:nth-child(1) {background-color: var(--color-blue-75);}.spin span:nth-child(2) {background-color: var(--color-blue);}.spin span:nth-child(3) {background-color: var(--color-blue-130);}.spin span:nth-child(4) {background-color: var(--color-grey-25);}',
	'KOL-PAGINATION':
		':host {--kolibri-spacing: var(--spacing-m);}:host {display: grid;gap: 1rem;}:host > div {display: inline-flex;flex-wrap: wrap;align-items: center;gap: 0.5em;}button > kol-span-wc {border: none;color: var(--color-black);font-weight: var(--font-weight-bold);}',
	'KOL-INPUT-CHECKBOX':
		'input[type="checkbox"] {background-color: var(--color-white);border-width: 2px;border-style: solid;color: var(--color-grey);line-height: 1.5em;font-size: 1rem;}input[type="checkbox"]:focus {outline-color: var(--color-blue);outline-offset: 2px;outline-style: solid;outline-width: 2px;}input[type="checkbox"] {border-color: var(--color-grey-75);}input[type="checkbox"]:checked {background-color: var(--color-blue);border-color: var(--color-blue);}input[type="checkbox"]:hover {border-color: var(--color-blue);}input[type="checkbox"]:checked:hover {background-color: var(--color-blue-130);border-color: var(--color-blue-130);}input[type="checkbox"]:indeterminate:hover::before {background-color: var(--color-blue-130);}.error input[type="checkbox"] {border-color: var(--color-red);}.error input[type="checkbox"]:checked {background-color: var(--color-red);border-color: var(--color-red);}.error input[type="checkbox"]:hover {border-color: var(--color-red);}.error input[type="checkbox"]:checked:hover {background-color: var(--color-red-1xx);border-color: var(--color-red-1xx);}.error input[type="checkbox"]:checked:hover::before {border-color: var(--color-white);}.error input[type="checkbox"]:indeterminate:hover::before {background-color: var(--color-red-1xx);}.error.required label > span::after {color: var(--color-red);}.switch input[type="checkbox"]::before,.switch input[type="checkbox"]:indeterminate::before {background-color: var(--color-grey-75);}.switch input[type="checkbox"]:hover::before,.switch input[type="checkbox"]:indeterminate:hover::before {background-color: var(--color-blue);}.switch input[type="checkbox"]:checked::before,.switch input[type="checkbox"]:checked:hover::before {background-color: var(--color-white);}.switch.error input[type="checkbox"]::before {background-color: var(--color-red);}.switch.error input[type="checkbox"]:checked::before {background-color: var(--color-white);}.switch.error input[type="checkbox"]:indeterminate:hover::before {background-color: var(--color-red-1xx);}kol-input {gap: var(--spacing-xs);}kol-input.error > kol-alert {color: var(--color-red);font-size: 0.875em;margin-left: calc(-1 * var(--spacing-2xs));order: 1;}kol-input.error > .input {order: 2;}kol-input.error > label {order: 3;}kol-input.error > .hint {font-size: 0.875rem;order: 4;}',
	'KOL-INPUT-COLOR': 'kol-input.error > kol-alert {color: var(--color-red);font-size: 0.875rem;margin-left: calc(-1 * var(--spacing-2xs));order: 1;}',
});
