name: Fehler melden
description: Alle relevanten Fehler, z. B. fehlerhafte Komponenten oder Beispiele
title: '🐞 Bug: '
labels: ['v2', 'v3']
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Eine klare und präzise Beschreibung des Fehlers und was du stattdessen erwartet hast.
      placeholder: Ich habe erwartet, dass A passiert, aber stattdessen habe ich B beobachtet.
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: 'URL zur Reproduktion'
      description: |
        Bitte gib die URL an, mit der sich das Problem reproduzieren lässt.

        StackBlitz-Starter-Templates:
        - **KoliBri (v2)** <https://stackblitz.com/edit/vitejs-vite-kkfhk5>
      placeholder: z. B. https://stackblitz.com/edit/XXXXXX
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Schritte zur Reproduktion
      description: |
        **Liste die exakten Schritte zur Reproduktion auf**: Je einfacher wir den Fehler nachstellen können, desto schneller können wir ihn beheben.
      placeholder: |
        1. Gehe zu '...'
        2. Klicke auf '...'
        3. Scrolle zu '...'
        4. Fehler erscheint
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: 'Screenshots'
      description: Falls zutreffend, füge Screenshots hinzu, um das Problem zu veranschaulichen.
      placeholder: Füge deine Screenshots hier ein
    validations:
      required: false
  - type: markdown
    attributes:
      value: '## Weitere Informationen'
  - type: dropdown
    id: affected_components
    attributes:
      label: Komponenten
      description: Wähle alle Komponenten aus, die vom Problem betroffen sind.
      multiple: true
      options:
        - 'Abbr'
        - 'Accordion'
        - 'Alert'
        - 'Avatar'
        - 'Badge'
        - 'Breadcrumb'
        - 'Button-Link'
        - 'Button'
        - 'Card'
        - 'Combobox'
        - 'Details'
        - 'Form'
        - 'Heading'
        - 'Icon'
        - 'Image'
        - 'Input-Checkbox'
        - 'Input-Color'
        - 'Input-Date'
        - 'Input-Email'
        - 'Input-File'
        - 'Input-Number'
        - 'Input-Password'
        - 'Input-Radio'
        - 'Input-Range'
        - 'Input-Text'
        - 'Link-Button'
        - 'Link'
        - 'Modal'
        - 'Nav'
        - 'Pagination'
        - 'Progress'
        - 'Quote'
        - 'Select'
        - 'Spin'
        - 'Split-Button'
        - 'Table'
        - 'Tabs'
        - 'Textarea'
        - 'Toast'
        - 'Toolbar'
        - 'Tree'
        - 'Version'
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: In welchen Browsern tritt das Problem auf?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
