/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SpinVariantPropType } from "./types/props/variant/spin";
export { SpinVariantPropType } from "./types/props/variant/spin";
export namespace Components {
    interface KolHydSpin {
        /**
          * Makes the element show up.
          * @TODO : Change type back to `ShowPropType` after Stencil#4663 has been resolved.
         */
        "_show"?: boolean;
        /**
          * Defines which variant should be used for presentation.
         */
        "_variant"?: SpinVariantPropType;
    }
}
declare global {
    interface HTMLKolHydSpinElement extends Components.KolHydSpin, HTMLStencilElement {
    }
    var HTMLKolHydSpinElement: {
        prototype: HTMLKolHydSpinElement;
        new (): HTMLKolHydSpinElement;
    };
    interface HTMLElementTagNameMap {
        "kol-hyd-spin": HTMLKolHydSpinElement;
    }
}
declare namespace LocalJSX {
    interface KolHydSpin {
        /**
          * Makes the element show up.
          * @TODO : Change type back to `ShowPropType` after Stencil#4663 has been resolved.
         */
        "_show"?: boolean;
        /**
          * Defines which variant should be used for presentation.
         */
        "_variant"?: SpinVariantPropType;
    }
    interface IntrinsicElements {
        "kol-hyd-spin": KolHydSpin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kol-hyd-spin": LocalJSX.KolHydSpin & JSXBase.HTMLAttributes<HTMLKolHydSpinElement>;
        }
    }
}
