const fs = require('fs');
const path = require('path');

const customElementsPath = path.resolve(__dirname, '../custom-elements.json');

if (!fs.existsSync(customElementsPath)) {
        console.warn('Skipping Blazor adapter generation because custom-elements.json is missing.');
        process.exit(0);
}

const elements = JSON.parse(fs.readFileSync(customElementsPath, 'utf8'));
const tags = Array.isArray(elements.tags) ? elements.tags : [];

const BLACKLIST = new Set([
        'kol-alert-wc',
        'kol-avatar-wc',
        'kol-color',
        'kol-counter',
        'kol-heading-wc',
        'kol-icon-font-awesome',
        'kol-icon-icofont',
        'kol-input-adapter-leanup',
        'kol-input-radio-group',
        'kol-span',
        'kol-span-wc',
]);

const outputRoot = path.resolve(__dirname, '../', 'adapters', 'blazor', 'src');
const componentsDir = path.join(outputRoot, 'Components');

fs.rmSync(outputRoot, { recursive: true, force: true });
fs.mkdirSync(componentsDir, { recursive: true });

const escapeXml = (value) => {
        return value
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;')
                .replace(/'/g, '&apos;');
};

const removeUnderscore = (value) => value.replace(/^_/u, '');

const pascalCase = (value) => {
        return removeUnderscore(value)
                .split(/[-:]/u)
                .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
                .join('');
};

const normalizeType = (type) => {
        if (!type) {
                return 'string?';
        }

        const tokens = type
                .split('|')
                .map((token) => token.trim().toLowerCase())
                .filter((token) => token.length > 0);

        const onlyBooleans = tokens.length > 0 && tokens.every((token) => token === 'boolean' || token === 'undefined' || token === 'null');
        if (onlyBooleans) {
                return 'bool?';
        }

        const onlyNumbers = tokens.length > 0 && tokens.every((token) => token === 'number' || token === 'undefined' || token === 'null');
        if (onlyNumbers) {
                return 'double?';
        }

        return 'string?';
};

const createSummary = (text) => {
        if (!text || typeof text !== 'string') {
                return '';
        }

        const content = escapeXml(text).split(/\r?\n/u).join('\n/// ');
        return `\t/// <summary>\n\t/// ${content}\n\t/// </summary>\n`;
};

const baseClassContent = `// <auto-generated />\nusing System.Collections.Generic;\nusing Microsoft.AspNetCore.Components;\n\nnamespace PublicUi.Kolibri.Blazor;\n\npublic abstract partial class KolibriComponentBase : ComponentBase\n{\n\tprivate IReadOnlyDictionary<string, object?> _attributes = new Dictionary<string, object?>(System.StringComparer.Ordinal);\n\n\t[Parameter(CaptureUnmatchedValues = true)]\n\tpublic IReadOnlyDictionary<string, object?>? AdditionalAttributes { get; set; }\n\n\t[Parameter]\n\tpublic RenderFragment? ChildContent { get; set; }\n\n\tprotected IReadOnlyDictionary<string, object?> Attributes => _attributes;\n\n\tprotected override void OnParametersSet()\n\t{\n\t\tvar attributes = new Dictionary<string, object?>(System.StringComparer.Ordinal);\n\n\t\tif (AdditionalAttributes is not null)\n\t\t{\n\t\t\tforeach (var attribute in AdditionalAttributes)\n\t\t\t{\n\t\t\t\tattributes[attribute.Key] = attribute.Value;\n\t\t\t}\n\t\t}\n\n\t\tBuildAttributes(attributes);\n\n\t\t_attributes = attributes;\n\t}\n\n\tprotected virtual void BuildAttributes(Dictionary<string, object?> attributes)\n\t{\n\t}\n\n\tprotected static void AddAttribute(Dictionary<string, object?> attributes, string name, object? value)\n\t{\n\t\tif (value is null)\n\t\t{\n\t\t\treturn;\n\t\t}\n\n\t\tattributes[name] = value;\n\t}\n}\n`;

const importsContent = `@using Microsoft.AspNetCore.Components\n@using System.Collections.Generic\n@using PublicUi.Kolibri.Blazor\n@namespace PublicUi.Kolibri.Blazor.Components\n`;

fs.writeFileSync(path.join(outputRoot, 'KolibriComponentBase.cs'), baseClassContent);
fs.writeFileSync(path.join(outputRoot, '_Imports.razor'), importsContent);

const componentTags = tags.filter((tag) => !BLACKLIST.has(tag.name));
componentTags.sort((a, b) => a.name.localeCompare(b.name));

componentTags.forEach((tag) => {
        const fileLines = [];
        fileLines.push('@inherits KolibriComponentBase');
        fileLines.push('');
        fileLines.push(`<${tag.name} @attributes="Attributes">`);
        fileLines.push('\t@ChildContent');
        fileLines.push(`</${tag.name}>`);
        fileLines.push('');
        fileLines.push('@code {');

        const attributes = Array.isArray(tag.attributes) ? [...tag.attributes] : [];
        attributes.sort((a, b) => a.name.localeCompare(b.name));

        const propertyNames = new Set();
        const buildStatements = [];

        attributes.forEach((attribute) => {
                const propertyName = pascalCase(attribute.name);
                if (propertyName.length === 0 || propertyNames.has(propertyName)) {
                        return;
                }
                propertyNames.add(propertyName);

                const propertyType = normalizeType(attribute.type);
                const summary = createSummary(attribute.description);

                if (summary) {
                        fileLines.push(summary.trimEnd());
                }

                fileLines.push('\t[Parameter]');
                fileLines.push(`\tpublic ${propertyType} ${propertyName} { get; set; }`);
                fileLines.push('');

                buildStatements.push(`\t\tAddAttribute(attributes, "${attribute.name}", ${propertyName});`);
        });

        if (buildStatements.length > 0) {
                fileLines.push('\tprotected override void BuildAttributes(Dictionary<string, object?> attributes)');
                fileLines.push('\t{');
                buildStatements.forEach((statement) => {
                        fileLines.push(statement);
                });
                fileLines.push('\t}');
        }

        fileLines.push('}');
        fileLines.push('');

        const componentPath = path.join(componentsDir, `${pascalCase(tag.name)}.razor`);
        fs.writeFileSync(componentPath, fileLines.join('\n'));
});

console.log(`Generated ${componentTags.length} Blazor component wrappers.`);
