npm deprecate @public-ui/core@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."
npm deprecate @public-ui/schema@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."
npm deprecate @public-ui/components@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."
npm deprecate @public-ui/themes@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."
npm deprecate @public-ui/angular@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."
npm deprecate @public-ui/preact@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."
npm deprecate @public-ui/react@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."
npm deprecate @public-ui/solid@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."
npm deprecate @public-ui/vue@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."

npm deprecate create-kolibri@$1 "Wir empfehlen die Verwendung einer neueren Version (>=$2)."
