npm deprecate @public-ui/core@$1 ""
npm deprecate @public-ui/schema@$1 ""
npm deprecate @public-ui/components@$1 ""
npm deprecate @public-ui/themes@$1 ""
npm deprecate @public-ui/angular-v11@$1 ""
npm deprecate @public-ui/angular-v12@$1 ""
npm deprecate @public-ui/angular-v13@$1 ""
npm deprecate @public-ui/angular-v14@$1 ""
npm deprecate @public-ui/angular-v15@$1 ""
npm deprecate @public-ui/preact@$1 ""
npm deprecate @public-ui/react@$1 ""
npm deprecate @public-ui/solid@$1 ""
npm deprecate @public-ui/vue@$1 ""

npm deprecate create-kolibri@$1 ""
