npm dist-tag $1 @public-ui/angular-v11@$2 $3
npm dist-tag $1 @public-ui/angular-v12@$2 $3
npm dist-tag $1 @public-ui/angular-v13@$2 $3
npm dist-tag $1 @public-ui/angular-v14@$2 $3
npm dist-tag $1 @public-ui/angular-v15@$2 $3
npm dist-tag $1 @public-ui/angular-v16@$2 $3
npm dist-tag $1 @public-ui/angular-v17@$2 $3
npm dist-tag $1 @public-ui/hydrate@$2 $3
npm dist-tag $1 @public-ui/kolibri-cli@$2 $3
npm dist-tag $1 @public-ui/preact@$2 $3
npm dist-tag $1 @public-ui/react@$2 $3
npm dist-tag $1 @public-ui/react-standalone@$2 $3
npm dist-tag $1 @public-ui/solid@$2 $3
npm dist-tag $1 @public-ui/vue@$2 $3
npm dist-tag $1 @public-ui/components@$2 $3
npm dist-tag $1 @public-ui/themes@$2 $3
npm dist-tag $1 @public-ui/theme-default@$2 $3
npm dist-tag $1 @public-ui/visual-tests@$2 $3

npm dist-tag $1 create-kolibri@$2 $3
