npm dist-tag $1 @public-ui/angular-v19@$2 $3
npm dist-tag $1 @public-ui/angular-v20@$2 $3
npm dist-tag $1 @public-ui/angular-v21@$2 $3
npm dist-tag $1 @public-ui/hydrate@$2 $3
npm dist-tag $1 @public-ui/kolibri-cli@$2 $3
npm dist-tag $1 @public-ui/mcp@$2 $3
npm dist-tag $1 @public-ui/preact@$2 $3
npm dist-tag $1 @public-ui/react@$2 $3
npm dist-tag $1 @public-ui/react-hook-form-adapter@$2 $3
npm dist-tag $1 @public-ui/react-v19@$2 $3
npm dist-tag $1 @public-ui/react-standalone@$2 $3
npm dist-tag $1 @public-ui/solid@$2 $3
npm dist-tag $1 @public-ui/svelte@$2 $3
npm dist-tag $1 @public-ui/vue@$2 $3
npm dist-tag $1 @public-ui/components@$2 $3
npm dist-tag $1 @public-ui/sample-react@$2 $3
npm dist-tag $1 @public-ui/theme-bwst@$2 $3
npm dist-tag $1 @public-ui/theme-default@$2 $3
npm dist-tag $1 @public-ui/theme-ecl@$2 $3
npm dist-tag $1 @public-ui/theme-kern@$2 $3
npm dist-tag $1 @public-ui/stylelint-rules@$2 $3
npm dist-tag $1 @public-ui/themes@$2 $3
npm dist-tag $1 @public-ui/visual-tests@$2 $3
