npx license-report --output=html --package=package.json >> license-reports/root.html
npx license-report --output=html --package=packages/adapters/angular/v19/package.json >> license-reports/adapter-angular-v19.html
npx license-report --output=html --package=packages/adapters/angular/v20/package.json >> license-reports/adapter-angular-v20.html
npx license-report --output=html --package=packages/adapters/angular/v21/package.json >> license-reports/adapter-angular-v21.html
npx license-report --output=html --package=packages/adapters/hydrate/package.json >> license-reports/adapter-hydrate.html
npx license-report --output=html --package=packages/adapters/preact/package.json >> license-reports/adapter-preact.html
npx license-report --output=html --package=packages/adapters/react/package.json >> license-reports/adapter-react.html
npx license-report --output=html --package=packages/adapters/react-standalone/package.json >> license-reports/adapter-react-standalone.html
npx license-report --output=html --package=packages/adapters/solid/package.json >> license-reports/adapter-solid.html
npx license-report --output=html --package=packages/adapters/svelte/package.json >> license-reports/adapter-svelte.html
npx license-report --output=html --package=packages/adapters/vue/package.json >> license-reports/adapter-vue.html
npx license-report --output=html --package=packages/components/package.json >> license-reports/components.html
npx license-report --output=html --package=packages/icons/package.json >> license-reports/icons.html
npx license-report --output=html --package=packages/samples/react/package.json >> license-reports/sample-react.html
npx license-report --output=html --package=packages/themes/default/package.json >> license-reports/theme-default.html
npx license-report --output=html --package=packages/themes/ecl/package.json >> license-reports/theme-ecl.html
npx license-report --output=html --package=packages/themes/kern/package.json >> license-reports/theme-kern.html
npx license-report --output=html --package=packages/themes/package.json >> license-reports/themes.html
npx license-report --output=html --package=packages/tools/kolibri-cli/package.json >> license-reports/tools-kolibri-cli.html
npx license-report --output=html --package=packages/tools/mcp/package.json >> license-reports/tools-mcp.html
npx license-report --output=html --package=packages/tools/visual-tests/package.json >> license-reports/tools-visual-tests.html
