npx license-report --output=html --package=package.json >> license-reports/root.html
npx license-report --output=html --package=packages/adapters/angular/v15/package.json >> license-reports/adapter-angular-v15.html
npx license-report --output=html --package=packages/adapters/angular/v16/package.json >> license-reports/adapter-angular-v16.html
npx license-report --output=html --package=packages/adapters/angular/v17/package.json >> license-reports/adapter-angular-v17.html
npx license-report --output=html --package=packages/adapters/hydrate/package.json >> license-reports/adapter-hydrate.html
npx license-report --output=html --package=packages/adapters/preact/package.json >> license-reports/adapter-preact.html
npx license-report --output=html --package=packages/adapters/react/package.json >> license-reports/adapter-react.html
npx license-report --output=html --package=packages/adapters/react-standalone/package.json >> license-reports/adapter-react-standalone.html
npx license-report --output=html --package=packages/adapters/solid/package.json >> license-reports/adapter-solid.html
npx license-report --output=html --package=packages/adapters/vue/package.json >> license-reports/adapter-vue.html
npx license-report --output=html --package=packages/components/package.json >> license-reports/components.html
npx license-report --output=html --package=packages/core/package.json >> license-reports/core.html
npx license-report --output=html --package=packages/create-kolibri/package.json >> license-reports/create-kolibri.html
npx license-report --output=html --package=packages/designer/package.json >> license-reports/designer.html
npx license-report --output=html --package=packages/samples/angular/package.json >> license-reports/sample-angular.html
npx license-report --output=html --package=packages/samples/react/package.json >> license-reports/sample-react.html
npx license-report --output=html --package=packages/samples/ssr/package.json >> license-reports/sample-ssr.html
npx license-report --output=html --package=packages/samples/vite/package.json >> license-reports/sample-vite.html
npx license-report --output=html --package=packages/storybook/package.json >> license-reports/storybook.html
npx license-report --output=html --package=packages/schema/package.json >> license-reports/schema.html
npx license-report --output=html --package=packages/themes/package.json >> license-reports/themes.html
npx license-report --output=html --package=packages/tools/kolibri-cli/package.json >> license-reports/themes.html
npx license-report --output=html --package=packages/tools/visual-tests/package.json >> license-reports/themes.html
