npx license-report --output=html --package=package.json >> license-reports/root.html
npx license-report --output=html --package=packages/adapters/angular/v11/package.json >> license-reports/adapter-angular-v11.html
npx license-report --output=html --package=packages/adapters/angular/v12/package.json >> license-reports/adapter-angular-v12.html
npx license-report --output=html --package=packages/adapters/angular/v13/package.json >> license-reports/adapter-angular-v13.html
npx license-report --output=html --package=packages/adapters/angular/v14/package.json >> license-reports/adapter-angular-v14.html
npx license-report --output=html --package=packages/adapters/angular/v15/package.json >> license-reports/adapter-angular-v15.html
npx license-report --output=html --package=packages/adapters/preact/package.json >> license-reports/adapter-preact.html
npx license-report --output=html --package=packages/adapters/react/package.json >> license-reports/adapter-react.html
npx license-report --output=html --package=packages/adapters/solid/package.json >> license-reports/adapter-solid.html
npx license-report --output=html --package=packages/adapters/svelte/package.json >> license-reports/adapter-svelte.html
npx license-report --output=html --package=packages/adapters/vue/package.json >> license-reports/adapter-vue.html
npx license-report --output=html --package=packages/create-kolibri/package.json >> license-reports/create-kolibri.html
npx license-report --output=html --package=packages/core/package.json >> license-reports/core.html
npx license-report --output=html --package=packages/library/package.json >> license-reports/library.html
npx license-report --output=html --package=packages/schema/package.json >> license-reports/schema.html
npx license-report --output=html --package=packages/storybook/package.json >> license-reports/storybook.html
npx license-report --output=html --package=packages/themes/package.json >> license-reports/themes.html
