npm unpublish @public-ui/angular-v17@$1
npm unpublish @public-ui/angular-v18@$1
npm unpublish @public-ui/angular-v19@$1
npm unpublish @public-ui/angular-v20@$1
npm unpublish @public-ui/hydrate@$1
npm unpublish @public-ui/kolibri-cli@$1
npm unpublish @public-ui/mcp@$1
npm unpublish @public-ui/preact@$1
npm unpublish @public-ui/react@$1
npm unpublish @public-ui/react-hook-form-adapter@$1
npm unpublish @public-ui/react-v19@$1
npm unpublish @public-ui/react-standalone@$1
npm unpublish @public-ui/solid@$1
npm unpublish @public-ui/svelte@$1
npm unpublish @public-ui/vue@$1
npm unpublish @public-ui/components@$1
npm unpublish @public-ui/sample-react@$1
npm unpublish @public-ui/theme-default@$1
npm unpublish @public-ui/theme-ecl@$1
npm unpublish @public-ui/theme-kern@$1
npm unpublish @public-ui/themes@$1
npm unpublish @public-ui/visual-tests@$1
