export const TAG_NAMES: string[] = [
	'kol-icon',
	// 'kol-icon-font-awesome', no shadow dom
	// 'kol-icon-icofont', no shadow dom
	'kol-badge',
	'kol-heading',
	'kol-accordion',
	'kol-alert',
	'kol-card',
	'kol-symbol',
	'kol-version',
	'kol-abbr',
	'kol-button',
	'kol-link-button',
	'kol-button-group',
	'kol-pagination',
	'kol-indented-text',
	'kol-input-checkbox',
	'kol-input-color',
	// 'kol-input-date', // not customizable
	'kol-input-file',
	'kol-input-email',
	'kol-input-number',
	'kol-input-password',
	'kol-input-radio',
	'kol-input-range',
	'kol-input-text',
	'kol-link',
	'kol-select',
	'kol-textarea',
	'kol-breadcrumb',
	'kol-details',
	'kol-form',
	// 'kol-input-adapter-leanup', // not customizable
	// 'kol-kolibri', // not customizable
	'kol-button-link',
	'kol-link-group',
	// 'kol-logo', // not customizable
	'kol-modal',
	'kol-nav',
	'kol-progress',
	'kol-skip-nav',
	'kol-spin',
	'kol-table',
	'kol-tabs',
	'kol-toast',
	'kol-tooltip',
];
