name: Definition of Done

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

concurrency:
  group: 'pr-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  check-dod:
    # Skip this job for draft pull requests as they are considered works in progress
    # or the base clone URL may be different than the head clone URL.
    if: |
      github.event.pull_request.draft == false &&
      github.event.pull_request.base.repo.clone_url == github.event.pull_request.head.repo.clone_url
    runs-on: ubuntu-latest
    steps:
      - name: Print Pull Request ID
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Check DoD
        uses: platisd/definition-of-done@master
        with:
          dod_yaml: '.github/dod.yml'
          message_header: 'The A11y and PO reviews will only take place after all other DoD steps have been completed by the Developer:'
          github_token: ${{ secrets.GITHUB_TOKEN }}
