name: Netlify Draft-Deploy

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: 'workflow-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}'
  cancel-in-progress: true

permissions:
  attestations: write
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    # Skip this job when the base clone URL may be different from the head clone URL.
    if: github.event.pull_request.head.repo.fork == false
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit
    with:
      environment: preview
