name: Scheduled Security Scan

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'

concurrency:
  group: ${{ format('workflow-{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  scheduled-scan:
    name: Scheduled Security Scan (${{ matrix.branch }})
    strategy:
      fail-fast: false
      matrix:
        branch: ['develop', 'release/3', 'release/2']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
          ref: ${{ matrix.branch }}

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Run security scans
        uses: public-ui/kolibri/.github/actions/security-scan@5cc50fb7d237644be4810da80bc3e05050a85cdf # develop
        with:
          install-deps: 'true'
