name: Netlify Stable-Deploy

on:
  push:
    branches:
      - 'develop'
      - 'release/*'
    tags:
      - latest
      - v2-latest
      - v1-latest

concurrency:
  group: 'workflow-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}'
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-netlify.yml
    with:
      environment: production
      alias: ${{ github.ref_name }}
