/**
 * Turns the generated font into the `kol-icon-theme` mixin the theme includes, and drops the
 * svgtofont output the theme does not serve.
 *
 * The mixin is needed because the generated `style.css` only ever reaches the document: the theme
 * loads it through `inject-assets.css`, which is a plain `<link>`. KoliBri's icons live in shadow
 * roots, and a document stylesheet does not cross that boundary — only the theme's own stylesheet,
 * which is adopted into every shadow root, does. So the document copy contributes the `@font-face`
 * (which is ignored inside a shadow root anyway) and this mixin contributes the class rules.
 *
 * Both halves come out of the same build, so the code points stay in sync by construction. They are
 * assigned by svgtofont in alphabetical order starting at U+EA01, which means adding one icon in
 * the middle of the set renumbers everything after it — a hand-maintained copy of this table would
 * silently drift into the wrong icons.
 */
import * as fs from 'node:fs';
import { createRequire } from 'node:module';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const resolveFrom = createRequire(import.meta.url);
const PACKAGE_ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const FONT_NAME = 'd-you-icons';
const OUTPUT_DIR = path.join(PACKAGE_ROOT, '..', 'assets', FONT_NAME);
const CARBON_ROOT = path.dirname(resolveFrom.resolve('@carbon/icons/package.json'));

/** `.kolicon-house::before { content: "\ea10"; }` → `['house', 'ea10']` */
const ICON_RULE = /\.kolicon-([a-z0-9-]+)::before\s*\{\s*content:\s*"\\([0-9a-f]+)";/g;

/* Everything the theme does not serve: the framework components and the legacy font formats. The
   `@font-face` in styles/ lists woff2, woff and ttf — every browser KoliBri supports reads one of
   them, and the eot/svg fallbacks are dead weight in the published package. */
const UNUSED = [
	'react',
	'vue',
	`${FONT_NAME}.symbol.svg`,
	`${FONT_NAME}.svg`,
	`${FONT_NAME}.eot`,
	`${FONT_NAME}.json`,
	'style.less',
	'style.module.less',
	'style.scss',
	'style.styl',
];

const styleFile = path.join(OUTPUT_DIR, 'style.css');
if (!fs.existsSync(styleFile)) {
	console.error(`No generated stylesheet at ${styleFile} – run the font build first.`);
	process.exit(1);
}

const icons = [...fs.readFileSync(styleFile, 'utf8').matchAll(ICON_RULE)].map(([, name, codePoint]) => ({ name, codePoint }));
const expected = Object.keys(JSON.parse(fs.readFileSync(path.join(PACKAGE_ROOT, 'icons.json'), 'utf8')));

if (icons.length !== expected.length) {
	console.error(`The generated stylesheet carries ${icons.length} icon rules, but icons.json names ${expected.length}.`);
	process.exit(1);
}

const rules = icons.map(({ name, codePoint }) => `\t.kolicon-${name}::before {\n\t\tcontent: '\\${codePoint}';\n\t}`).join('\n\n');

const mixin = `/*
 * Generated by @public-ui/d-you-icons – do not edit.
 *
 * Rebuild with \`pnpm --filter @public-ui/d-you-icons build\`; \`icons.json\` in that package decides
 * which Carbon icon each KoliBri icon name resolves to.
 */
@mixin kol-icon-theme {
	[class^='kolicon-'],
	[class*=' kolicon-'] {
		font-family: '${FONT_NAME}';
		font-style: normal;
		font-weight: 400;
		line-height: 1em;
	}

${rules}
}
`;

fs.writeFileSync(path.join(OUTPUT_DIR, '_mixin.scss'), mixin);

for (const entry of UNUSED) {
	fs.rmSync(path.join(OUTPUT_DIR, entry), { recursive: true, force: true });
}

/* The font is a derivative work of the Carbon SVGs, and Apache-2.0 §4(a) asks whoever distributes
   one to hand the recipient the license along with it. Every other asset folder of a KoliBri theme
   keeps its license file next to it for the same reason, so the Carbon text goes here rather than
   only into the theme's NOTICE.md. */
fs.copyFileSync(path.join(CARBON_ROOT, 'LICENSE'), path.join(OUTPUT_DIR, 'LICENSE'));

console.log(`Wrote _mixin.scss with ${icons.length} icons to ${path.relative(PACKAGE_ROOT, OUTPUT_DIR)}.`);
